# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-27 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191203_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии к статьям блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 2, 27, 17, 49, 7, 881432), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 2, 27, 17, 49, 7, 883433), verbose_name='Дата'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comments',
        ),
    ]
