# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-27 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200227_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 2, 27, 18, 9, 20, 27320), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 2, 27, 18, 9, 20, 28320), verbose_name='Дата'),
        ),
    ]
